name: Documentation Issue
description: Report an issue or request a change
body:
  - type: input
    id: endpoint
    attributes:
      label: Endpoint
      placeholder: /users/{id}
  - type: textarea
    id: details
    attributes:
      label: Details
